<div class="offcanvas-wrapper">
  <div class="container padding-top-3x padding-bottom-3x mb-1"><img class="d-block m-auto" src="<?php echo Config::mostrar('PASTA_MISC'); ?>img/404_art.jpg" style="width: 100%; max-width: 550px;" alt="404">
    <div class="padding-top-1x mt-2 text-center">
      <h3>Página não encontrada</h3>
      <p>Não conseguimos encontrar a página que você estava procurando. <a href="<?php echo Config::mostrar('PASTA_PADRAO'); ?>">Voltar à página inicial.</a></p>
    </div>
</div>
