<div class="wrapper">
 <header class="main-header">
   <a href="" class="logo">
     <span class="logo-mini"><b>J</b>A</span>
     <span class="logo-lg"><b>JA</b>Solutions</span>
   </a>
   <nav class="navbar navbar-static-top" role="navigation">
     <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
       <span class="sr-only">Toggle navigation</span>
     </a>
   </nav>
 </header>
 <aside class="main-sidebar">
   <section class="sidebar">
     <div class="user-panel">
       <div class="pull-left info">
         <p><?php echo Admin::mostrar('nome'); ?></p>
         <br>
         <hr>
       </div>
     </div>

     <ul class="sidebar-menu" data-widget="tree">
         <?php Admin::montarMenu(); ?>
     </ul>
   </section>
 </aside>
