  </section>
  </div>
    <footer class="main-footer">
      <strong>Copyright &copy; <?php echo date('Y'); ?> <a href="https://www.joaoartur.com/">João Artur</a>.</strong> Todos os direitos reservados.
    </footer>
  </div>
  </aside>
  <?php
    Load::js('jquery.js',true);
    Load::js('bower_components/bootstrap/dist/js/bootstrap.min.js',true);
    Load::js('dist/js/adminlte.min.js',true);

    Load::mostrarJS();
  ?>
</body>
</html>
