  </section>
  </div>
    <footer class="main-footer">
      <strong>Copyright &copy; <?php echo date('Y'); ?> <a href="https://www.joaoartur.com/">João Artur</a>.</strong> Todos os direitos reservados.
    </footer>
  </div>
  </aside>
  <script src="<?=Config::show('ADMIN_MISC');?>js/jquery.js"></script>
  <script src="<?=Config::show('ADMIN_MISC');?>bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
  <script src="<?=Config::show('ADMIN_MISC');?>dist/js/adminlte.min.js"></script>
</body>
</html>
