<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Administração | <?php echo \JetPHP\Model\Config::show('TITULO'); ?></title>
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

  <link rel="stylesheet" href="<?=\JetPHP\Model\Config::show('ADMIN_MISC');?>bower_components/bootstrap/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="<?=\JetPHP\Model\Config::show('ADMIN_MISC');?>bower_components/font-awesome/css/font-awesome.min.css">
  <link rel="stylesheet" href="<?=\JetPHP\Model\Config::show('ADMIN_MISC');?>bower_components/Ionicons/css/ionicons.min.css">
  <link rel="stylesheet" href="<?=\JetPHP\Model\Config::show('ADMIN_MISC');?>dist/css/AdminLTE.min.css">
  <link rel="stylesheet" href="<?=\JetPHP\Model\Config::show('ADMIN_MISC');?>dist/css/skins/_all-skins.css">
  <link rel="stylesheet" href="<?=\JetPHP\Model\Config::show('ADMIN_MISC');?>dist/css/padrao.css">
  
  <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition skin-black sidebar-mini">
