<div class="container">
  <div class="row">
    <div class="col-8 offset-2 text-center">
      <h1>JetPHP</h1>
      <p>PHP Framework for full-stack websites and systems</p>
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col-8 offset-2">
      <p>
        Thank you for downloading JetPHP Framework, now let's install!
        <br>
        First use <b>composer</b> to install dependencies:
      </p>
    </div>
    <div class="col-8 offset-2" style="background: #f9f9f9">
      <code>
        composer install-framework
      </code>
    </div>
  </div>
</div>
