<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title><?php echo Config::show('TITULO'); ?></title>

    <?php SEO::ready(); ?>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    <link rel="stylesheet" href="misc/css/bootstrap.css">
    <link rel="stylesheet" href="misc/css/padrao.css">
    <script src="misc/js/jquery.js"></script>
    <script src="misc/js/bootstrap.js"></script>
  </head>
  <body>
