    <div class="container">
      <div class="row">
        <div class="col-6 offset-3 text-center">
          <div id="centro">
            <h1>JetPHP</h1>
            <p>O framework gaúcho que veio para facilitar o desenvolvimento de seus sites e sistemas!</p>
            <a href="https://github.com/JoaoArtur/JetPHP">Documentação</a>
          </div>
        </div>
      </div>
    </div>
<form class="" action="" method="post">
  <div class="row">
    <div class="col-md-3">
      <input type="text" name="usuario" class="form-control" placeholder="Digite seu nome">
    </div>
  </div>
  <?php JCaptchaInput::gerarCampo(); ?>
  <input type="submit" name="" value="Enviar" class="btn btn-success">
</form>
<?php if (isset($_POST['usuario'])) {echo Entrada::post('usuario');} ?>
