<div class="container">
  <div class="row">
    <div class="col-8 offset-2 text-center">
      <h1>JetPHP</h1>
      <p>Framework gaúcho com foco em desenvolvimento de sites e sistemas em PHP</p>
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col-8 offset-2">
      <p>
        Seja bem vindo à instalação do JetPHP!
        <br>
        Primeiramente, você deve instalar os repositórios utilizando o <b>composer</b>:
      </p>
    </div>
    <div class="col-8 offset-2" style="background: #f9f9f9">
      <code>
        composer instalar
      </code>
    </div>
  </div>
</div>
