<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Administração | <?php echo Config::show('TITULO'); ?></title>
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <?php
    Load::css('bower_components/bootstrap/dist/css/bootstrap.min.css',true);
    Load::css('bower_components/font-awesome/css/font-awesome.min.css',true);
    Load::css('bower_components/Ionicons/css/ionicons.min.css',true);
    Load::css('dist/css/AdminLTE.min.css',true);
    Load::css('dist/css/skins/_all-skins.css',true);
    Load::css('padrao.css',true);

    Load::mostrarCSS();
  ?>
  <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition skin-black sidebar-mini">
