<div class="login-box">
  <div class="login-logo">
    <a href="../../index2.html"><b>JA</b>Solutions</a>
  </div>
  <div class="login-box-body">
    <p class="login-box-msg">Entre na sua conta para gerenciar o sistema</p>

    <form method="post">
      <div class="form-group has-feedback">
        <input type="text" name="usuario" class="form-control" placeholder="Usuário">
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        <input type="password" class="form-control" placeholder="Senha" name="senha">
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>
      <div class="row">
        <div class="col-xs-4 pull-right">
          <button type="submit" class="btn btn-primary btn-block btn-flat">Entrar</button>
        </div>
      </div>
    </form>
  </div>
</div>
